
name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r24
        add-to-path: false

    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      # run: ./gradlew build
      run: ./gradlew assembleRelease

    - name: Upload GitHub Actions artifact of vcpkg build
      uses: actions/upload-artifact@v2
      with:
        name: scene-dev
        path: ${{ github.workspace }}/app/build/outputs/apk/release/app-release.apk

    - name: Deploy
      env: 
        GITHUB_REPO: github.com/Verdial/vtools-dev-apks.git
      run: |
        cd ${{ github.workspace }}/app/build/outputs/apk/release/
        git push --force --quiet "https://${{ secrets.ACCESS_TOKEN }}@$GITHUB_REPO" master:master
